export interface MenuItem {
  id: string;
  name: string;
  nameAr: string;
  description?: string;
  descriptionAr?: string;
  price: number;
  variants?: { name: string; nameAr: string; price: number }[];
}

export interface MenuCategory {
  id: string;
  name: string;
  nameAr: string;
  icon: string;
  image: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: "hot-coffee",
    name: "Hot Coffee",
    nameAr: "قهوة",
    icon: "",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80",
   items: [
      { id: "turkish-coffee", name: "Turkish Coffee", nameAr: "قهوة تركي", price: 40 },
      { id: "double-turkish", name: "Double Turkish Coffee", nameAr: "قهوة تركي دبل", price: 45 },
      { id: "french-coffee", name: "French Coffee", nameAr: "قهوة فرنسي", price: 50 },
      { id: "double-french", name: "Double French Coffee", nameAr: "قهوة فرنسي دبل", price: 55 },
      { id: "cafe-latte", name: "Cafe Latte", nameAr: "كافيه لاتيه", description: "Vanilla-Caramel-Hazelnut +5 EGP", descriptionAr: "اضافة سيرب 5 جنيه", price: 65 },
      { id: "cappuccino", name: "Cappuccino", nameAr: "كابتشينو", description: "Vanilla-Caramel-Hazelnut +5 EGP", descriptionAr: "اضافة سيرب 5 جنيه", price: 70 },
      { id: "espresso", name: "Espresso", nameAr: "اسبريسو", price: 45 },
      { id: "double-espresso", name: "Double Espresso", nameAr: "اسبريسو دبل", price: 55 },
      { id: "macchiato", name: "Macchiato", nameAr: "ميكاتو", price: 50 },
      { id: "double-macchiato", name: "Double Macchiato", nameAr: "ميكاتو دبل", price: 55 },
      { id: "caramel-macchiato", name: "Caramel Macchiato", nameAr: "ميكاتو كراميل", price: 60 },
      { id: "american-coffee", name: "American Coffee", nameAr: "آمريكان كوفي", price: 50 },
      { id: "nescafe", name: "Nescafe", nameAr: "نسكافيه", price: 50 },
      { id: "nescafe-milk", name: "Nescafe Milk", nameAr: "نسكافيه حليب", price: 55 },
      { id: "cookies-latte", name: "Cookies Latte", nameAr: "كوكيز لاتيه", price: 70 },
      { id: "caramel-latte", name: "Caramel Latte", nameAr: "لاتيه كراميل", price: 55 },
      { id: "cafe-mocha", name: "Cafe Mocha", nameAr: "كافيه موكا", price: 70 },
      { id: "popcorn-latte", name: "Popcorn Latte", nameAr: "لاتيه فشار", price: 65 },
      { id: "brownie-latte", name: "Brownie Latte", nameAr: "براوني لاتيه", price: 65 },
      { id: "lotus-latte", name: "Lotus Latte", nameAr: "لوتس لاتيه", price: 70 },
      { id: "hot-chocolate", name: "Hot Chocolate", nameAr: "هوت شوكلت", description: "Vanilla-Caramel-Hazelnut +5 EGP", descriptionAr: "اضافة سيرب 5 جنيه", price: 55 },
      { id: "espresso-avocado", name: "Espresso Avocado", nameAr: "اسبريسو افوكادو", price: 70 },
      { id: "classic-cortado", name: "Classic Cortado", nameAr: "كورتادو كلاسيك", price: 60 },
      { id: "mocha-cortado", name: "Mocha Cortado", nameAr: "كورتادو موكا", price: 70 },
      { id: "hot-spanish-latte", name: "Hot Spanish Latte", nameAr: "هوت اسبانش لاتيه", price: 85 },
      { id: "espresso-con-panna", name: "Espresso Con Panna", nameAr: "اسبريسو كون بانا", price: 60 },
    ],
  },
  {
    id: "hot-drinks",
    name: "Hot Drinks",
    nameAr: "مشروبات ساخنة",
    icon: "",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcSlJCs8cLAFzcMxgODDB5qfG6Svknr6VjuA&s?w=400&q=80",
    items: [
      { id: "red-tea", name: "Red Tea", nameAr: "شاي أحمر", price: 30 },
      { id: "green-tea", name: "Green Tea", nameAr: "شاي أخضر", price: 30 },
      { id: "flavored-tea", name: "Flavored Tea", nameAr: "شاي نكهات", price: 35 },
      { id: "brad-tea", name: "Brad Tea", nameAr: "براد شاي", price: 30 },
      { id: "tea-milk", name: "Tea with Milk", nameAr: "شاي بالحليب", price: 35 },
      { id: "lemon-ginger", name: "Lemon Ginger", nameAr: "ليمون بالجنزبيل", price: 35 },
      { id: "cinnamon", name: "Cinnamon", nameAr: "قرفة", price: 35 },
      { id: "herbs", name: "Herbs", nameAr: "أعشاب", price: 40 },
      { id: "mint", name: "Mint", nameAr: "نعناع", price: 30 },
      { id: "sahlab", name: "Sahlab", nameAr: "سحلب", price: 50 },
      { id: "sahlab-fruits", name: "Sahlab Fruits", nameAr: "سحلب فواكه", price: 60 },
      { id: "sahlab-nuts", name: "Sahlab Nuts", nameAr: "سحلب مكسرات", price: 55 },
      { id: "sahlab-oreo", name: "Sahlab Nuts", nameAr: "سحلب اوريو", price: 60 },
      { id: "hot-sedar", name: "Hot Sedar", nameAr: "هوت سيدار", price: 50 },
      { id: "anise-tea", name: "Anise Tea", nameAr: "يانسون", price: 30 },
      { id: "hibiscus", name: "Hibiscus", nameAr: "كركديه", price: 35},
      { id: "mint-tea", name: "Mint Tea", nameAr: "شاي نعناع", price: 35 },
    ],
  },
  {
    id: "fresh-juice",
    name: "Fresh Juice",
    nameAr: "عصير فريش",
    icon: "",
    image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&q=80",
    items: [
      { id: "orange", name: "Orange", nameAr: "برتقال", price: 50 },
      { id: "mango", name: "Mango", nameAr: "مانجو", price: 65 },
      { id: "strawberry", name: "Strawberry", nameAr: "فراولة", price: 60 },
      { id: "lemon", name: "Lemon", nameAr: "ليمون", price: 45 },
      { id: "mint-lemon", name: "Mint Lemon", nameAr: "ليمون بالنعناع", price: 50 },
      { id: "kiwi", name: "Kiwi", nameAr: "كيوي", price: 80 },
      { id: "watermelon", name: "Watermelon", nameAr: "بطيخ", price: 60 },
      { id: "yogurt", name: "Yogurt", nameAr: "زبادي", price: 55 },
      { id: "fruit-yogurt", name: "Fruit Yogurt", nameAr: "زبادي فواكه", price: 70 },
      { id: "banana-milk", name: "Banana with Milk", nameAr: "موز بالحليب", price: 60 },
      { id: "dates-milk", name: "Dates with Milk", nameAr: "بلح بالحليب", price: 55 },
      { id: "guava", name: "Guava", nameAr: "جوافه", price: 55 },
      { id: "guava-milk", name: "Guava with Milk", nameAr: "جوافة بالحليب", price: 60 },
      { id: "strawberry-milk", name: "Strawberry with Milk", nameAr: "فراولة بالحليب", price: 60 },
    ],
  },
  {
    id: "cocktail",
    name: "Cocktail",
    nameAr: "كوكتيل",
    icon: "",
    image: "https://images.unsplash.com/photo-1546171753-97d7676e4602?w=400&q=80",
   items: [
      { id: "da-bomba", name: "Da Bomba", nameAr: "دا بومبا", description: "Mango-Strawberry-Kiwi-Banana", descriptionAr: "مانجو - فراولة - كيوي - موز", price: 95 },
      { id: "mango-kiwi", name: "Mango Kiwi", nameAr: "كيوي مانجا", price: 85 },
      { id: "kiwi-banana", name: "Kiwi Banana", nameAr: "كيوي موز", price: 75 },
      { id: "florida", name: "Florida", nameAr: "فلوريدا", price: 65 },
      { id: "strawberry-banana", name: "Strawberry Banana", nameAr: "كوكتيل فراولة موز", price: 65 },
      { id: "mix-ice-cream", name: "Mix Ice Cream", nameAr: "آيس كريم ميكس ", price: 65 },
      { id: "fruit-salad", name: "Fruit Salad", nameAr: "سلطة فواكه", price: 75 },
      { id: "ice-cream-1", name: "Ice Cream 1 Scoop", nameAr: "1 بولة آيس كريم", price: 25 },
      { id: "ice-cream-2", name: "Ice Cream 2 Scoop", nameAr: "2 بولة آيس كريم", price: 40 },
      { id: "ice-cream-3", name: "Ice Cream 3 Scoop", nameAr: "3 بولة آيس كريم", price: 50 },
      { id: "havana", name: "Havana", nameAr: "هافانا", description: "Mango-Ice Cream-Topping-Peach", descriptionAr: "مانجو - ايس كريم - توبيج خوخ", price: 75 },
      { id: "milano", name: "Milano", nameAr: "ميلانو", description: "Strawberry-Kiwi-Banana-Milk", descriptionAr: "فراولة - كيوي - موز - لبن", price: 90 },
      { id: "banana-jungle", name: "Banana Jungle", nameAr: "بانانا جانجل", description: "Strawberry-Banana-Milk-Ice Cream", descriptionAr: "فراولة - موز - لبن - آيس كريم", price: 75 },
      { id: "bower-nutella", name: "Bower Nutella", nameAr: "باور نوتيلا", description: "Nutella-Banana-Milk", descriptionAr: "نوتيلا - موز - لبن", price: 70 },
      { id: "roof-cocktail", name: "Roof Cocktail", nameAr: "كوكتيل روف", description: "Mango-Banana-Caramel Sauce-Ice Cream", descriptionAr: "مانجو - موز - صوص كراميل - آيس كريم", price: 80 },
      { id: "blue-whale", name: "Blue Whale", nameAr: "الحوت الازرق", description: "Mango-Blue Curacao-Ice Cream", descriptionAr: "مانجو - بلو كوراساو - آيس كريم", price: 70 },
      { id: "pina-colada", name: "Pina Colada", nameAr: "بينا كولادا", description: "Coconut Flavor-Pineapple Juice-Ice Cream", descriptionAr: "فليفر جوزهند - عصير اناناس - آيس كريم", price: 75 },
    ],
  },
  {
    id: "summer-drinks",
    name: "Summer Drinks",
    nameAr: "مشروبات الصيف",
    icon: "",
    image: "https://images.unsplash.com/photo-1560526860-1f0e56046c85?w=400&q=80",
    items: [
      { id: "watermelon-summer", name: "Watermelon", nameAr: "بطيخ", price: 60 },
      { id: "watermelon-mint", name: "Watermelon Mint", nameAr: "بطيخ نعناع", price: 65 },
      { id: "watermelon-milkshake", name: "Watermelon Milkshake", nameAr: "بطيخ ميلك شيك", price: 80 },
      { id: "milkshake-blueberry", name: "Milkshake Blueberry", nameAr: "ميلك شيك بلوبيري", price: 80 },
      { id: "blueberry-smoothie", name: "Blueberry Smoothie", nameAr: "سموزي بلوبيري", price: 55 },
      { id: "blueberry-yogurt", name: "Blueberry Yogurt", nameAr: "زبادي بلوبيري", price: 70},
      { id: "mango-colada", name: "Mango Colada", nameAr: "مانجو كولادا", price: 65 },
      { id: "coconut-banana", name: "Coconut Banana", nameAr: "جوز هند بالموز", price: 60 },
      { id: "sunshine", name: "Sunshine", nameAr: "صن شاين", price: 70 },
      { id: "cherry-cola", name: "Cherry Cola", nameAr: "شيري كولا", price: 65 },
      { id: "mojito-mint", name: "Mojito Mint", nameAr: "موهيتو نعناع", price: 70 },
      { id: "sunshine-red-bull", name: "Sunshine Red Bull", nameAr: "صن شاين ريد بول", price: 120 },
    ],
  },  
  {
  id: "mojito",
  name: "Mojito",
  nameAr: "موهيتو",
  icon: "",
  image: "https://png.pngtree.com/thumb_back/fh260/background/20240912/pngtree-side-view-mojito-cocktail-with-mint-lime-ice-bucket-image_16167746.jpg?w=400&q=80",
  items: [
    { id: "strawberry-mojito", name: "Strawberry Mojito", nameAr: "موهيتو فراولة", descriptionAr: "سيرب فراولة - ليمون - نعناع - آيس - سفن اب", price: 70 },
    { id: "blueberry-mojito", name: "Blueberry Mojito", nameAr: "موهيتو بلوبيري", descriptionAr: "سيرب بلوبيري - ليمون - نعناع - آيس - سفن اب", price: 70 },
    { id: "peach-mojito", name: "Peach Mojito", nameAr: "موهيتو خوخ", descriptionAr: "سيرب خوخ - ليمون - نعناع - آيس - سفن اب", price: 70 },
    { id: "pomegranate-mojito", name: "Pomegranate Mojito", nameAr: "موهيتو رمان", descriptionAr: "سيرب رمان - ليمون - نعناع - آيس - سفن اب", price: 70 },
    { id: "strawberry-pomegranate-mojito", name: "Strawberry Pomegranate Mojito", nameAr: "موهيتو رمان فراولة", descriptionAr: "رمان وفراولة - ليمون فرش - نعناع فرش - آيس - سفن اب", price: 70 },
    { id: "watermelon-mojito", name: "Watermelon Mojito", nameAr: "موهيتو بطيخ", descriptionAr: "سيرب بطيخ - ليمون - نعناع - آيس - سفن اب", price: 70 },
    { id: "blue-orange-mojito", name: "Blue Orange Mojito", nameAr: "موهيتو بلو اورنج", descriptionAr: "بلو كراسو - برتقال فرش - ليمون - نعناع - آيس - سفن اب", price: 75 },
    { id: "passion-mojito", name: "Passion Mojito", nameAr: "موهيتو باشون", descriptionAr: "باشون - بلو كراسو - ليمون - نعناع - آيس - سفن اب", price: 80 },
    { id: "redbull-mojito", name: "Red Bull Mojito", nameAr: "موهيتو ريدبول", descriptionAr: "ريد بول - ليمون - نعناع - آيس", price: 115 },
    { id: "pina-colada-mojito", name: "Pina Colada Mojito", nameAr: "موهيتو بيناكولادا", descriptionAr: "اناناس - جوز هند - ليمون - نعناع - سفن اب", price: 95 },
    { id: "blue-eyes-mojito", name: "Blue Eyes Mojito", nameAr: "موهيتو بلو آيس", descriptionAr: "اناناس - بلو كراسو - ليمون - نعناع - سفن اب", price: 95 },
    { id: "ice-tea", name: "Ice Tea", nameAr: "شاي مثلج", descriptionAr: "شاي ليبتون - سيرب - آيس - (الطعم من اختيارك)", price: 65 }
  ]
},
  {
    id: "frappe",
    name: "Frappe",
    nameAr: "فرابيه",
    icon: "",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",
    items: [
      { id: "mocha-frappe", name: "Mocha Frappe", nameAr: "موكا فرابيه", price: 65 },
      { id: "lotus-frappe", name: "Lotus Frappe", nameAr: "لوتس فرابيه", price: 80 },
      { id: "caramel-frappe", name: "Caramel Frappe", nameAr: "كراميل فرابيه", price: 65 },
      { id: "oreo-frappe", name: "Oreo Frappe", nameAr: "اوريو فرابيه", price: 80 },
      { id: "pistachio-frappe", name: "Pistachio Frappe", nameAr: "بستاشيو فرابيه", price: 90 },
      { id: "nautic-frappe", name: "Nautic Frappe", nameAr: "نوتيلا فرابيه", price: 80 },
    ],
  },
  {
    id: "frappuccino",
    name: "Frappuccino",
    nameAr: "فرابتشينو",
    icon: "",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80",
    items: [
      { id: "mocha-frappuccino", name: "Mocha Frappuccino", nameAr: "موكا فرابتشينو", price: 65 },
      { id: "caramel-frappuccino", name: "Caramel Frappuccino", nameAr: "فرابتشينو كراميل", price: 65 },
      { id: "mocha-caramel-frappuccino", name: "Mocha Caramel Frappuccino", nameAr: "فرابتشينو موكا كراميل", price: 70 },
      { id: "vanilla-frappuccino", name: "Vanilla Frappuccino", nameAr: "فرابتشينو فانيليا", price: 70 },
      { id: "lotus-frappuccino", name: "Lotus Frappuccino", nameAr: "فرابتشينو لوتس", price: 75 },
    ],
  },
  {
    id: "milkshake",
    name: "Milkshake",
    nameAr: "ميلك شيك",
    icon: "",
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400&q=80",
    items: [
      { id: "vanilla-milkshake", name: "Vanilla Milkshake", nameAr: "ميلك شيك فانيليا", price: 70 },
      { id: "oreo-milkshake", name: "Oreo Milkshake", nameAr: "ميلك شيك اوريو", price: 75 },
      { id: "snickers-milkshake", name: "Snickers Milkshake", nameAr: "ميلك شيك اسنيكرز", price: 85 },
      { id: "kitkat-milkshake", name: "KitKat Milkshake", nameAr: "ميلك شيك كت كات", price: 85 },
      { id: "lotus-milkshake", name: "Lotus Milkshake", nameAr: "ميلك شيك لوتس", price: 85 },
      { id: "chocolate-milkshake", name: "Chocolate Milkshake", nameAr: "ميلك شيك شوكولاتة", price: 70 },
      { id: "strawberry-milkshake", name: "Strawberry Milkshake", nameAr: "ميلك شيك فراولة", price: 70 },
      { id: "strawberry-banana-milkshake", name: "Strawberry Banana Milkshake", nameAr: "ميلك شيك فراولة و موز", price: 75 },
      { id: "banana-milkshake", name: "Banana Milkshake", nameAr: "ميلك شيك موز", price: 70 },
      { id: "mango-milkshake", name: "Mango Milkshake", nameAr: "ميلك شيك مانجا", price: 75 },
      { id: "popcorn-milkshake", name: "Popcorn Milkshake", nameAr: "ميلك شيك فشار", price: 75 },
      { id: "pistachio-milkshake", name: "Pistachio Milkshake", nameAr: "ميلك شيك بستاشيو", price: 85 },
      { id: "kinder-milkshake", name: "Kinder Milkshake", nameAr: "ميلك شيك كيندر", price: 95 },
      { id: "nutella-milkshake", name: "Nutella Milkshake", nameAr: "ميلك شيك نوتيلا", price: 85 },
      { id: "galaxy-milkshake", name: "Galaxy Milkshake", nameAr: "ميلك شيك جالاكسي", price: 95 },
      { id: "coffee-milkshake", name: "Coffee Milkshake", nameAr: "ميلك شيك كوفي", price: 75 },
    ],
  },
  {
    id: "smoothie",
    name: "Smoothie",
    nameAr: "سموذي",
    icon: "",
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&q=80",
    items: [
      { id: "mango-smoothie", name: "Mango Smoothie", nameAr: "سموزي مانجا", price: 55 },
      { id: "kiwi-smoothie", name: "Kiwi Smoothie", nameAr: "سموزي كيوي", price: 65 },
      { id: "banana-strawberry-smoothie", name: "Banana Strawberry Smoothie", nameAr: "سموزي موز وفراولة", price: 60 },
      { id: "banana-kiwi-smoothie", name: "Banana Kiwi Smoothie", nameAr: "سموزي موز وكيوي", price: 70 },
      { id: "strawberry-smoothie", name: "Strawberry Smoothie", nameAr: "سموزي فراولة", price: 55 },
    ],
  },
  {
    id: "ice-coffee",
    name: "Ice Coffee",
    nameAr: "آيس كوفي",
    icon: "",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&q=80",
    items: [
      { id: "ice-latte", name: "Ice Latte", nameAr: "آيس لاتيه", price: 55 },
      { id: "ice-mocha", name: "Ice Mocha", nameAr: "آيس موكا", price: 60 },
      { id: "ice-american", name: "Ice American", nameAr: "آيس امريكانا", price: 50 },
      { id: "ice-chocolate", name: "Ice Chocolate", nameAr: "شوكلت كوكيز موكا", price: 65 },
      { id: "ice-caramel-latte", name: "Ice Caramel Latte", nameAr: "آيس كراميل لاتيه", price: 60 },
      { id: "ice-latte-mial", name: "Ice Latte Mial", nameAr: "آيس لاتيه ميال", price: 70 },
      { id: "ice-white-mocha", name: "Ice White Mocha", nameAr: "آيس وايت موكا", price: 65 },
      { id: "ice-spanish-latte", name: "Ice Spanish Latte", nameAr: "آيس اسبانش لاتيه", price: 90 },
      { id: "ice-strawberry-latte", name: "Ice Strawberry Latte", nameAr: "آيس ستروبري لاتيه", price: 75 },
      { id: "ice-orange-latte", name: "Ice Orange Latte", nameAr: "آيس اورنج لاتيه", price: 90 },
      { id: "ice-chocolate-dark", name: "Ice Chocolate", nameAr: "آيس شوكلت", price: 65 },
      { id: "ice-white-chocolate", name: "Ice White Chocolate", nameAr: "آيس وايت شوكلت", price: 65 },
      { id: "pistachio-coffee", name: "Pistachio Coffee", nameAr: "بستاشيو كوفي", price: 85 },
      { id: "lotus-coffee", name: "Lotus Coffee", nameAr: "لوتس كوفي", price: 80 },
      { id: "nutella-coffee", name: "Nutella Coffee", nameAr: "نوتيلا كوفي", price: 85 },
    ],
  },
  {
    id: "soft-drinks",
    name: "Soft Drinks",
    nameAr: "سوفت درينك",
    icon: "",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGqzFnvoGNGkzJNpuZlsCguDcJHIWZlzlkww&s?w=400&q=80",
    items: [
      { id: "pepsi", name: "Pepsi", nameAr: "بيبسي", price: 40 },
      { id: "7up", name: "7UP", nameAr: "سيفين", price: 40 },
      { id: "fanta", name: "Fanta", nameAr: "فانتا", price: 40 },
      { id: "red-bull", name: "Red Bull", nameAr: "ريد بول", price: 75 },
      { id: "birell", name: "Birell", nameAr: "بريل", price: 40 },
      { id: "schweppes", name: "Schweppes", nameAr: "شوبيس", price: 40 },
      { id: "fayrouz", name: "Fayrouz", nameAr: "فيروز", price: 40 },
      { id: "water-s", name: "Water Small", nameAr: "مياه صغيرة", price: 15 },
      { id: "water-l", name: "Water Large", nameAr: "مياه كبيرة", price: 20 },
      { id: "sting", name: "Sting", nameAr: "ستينج", price: 40 },
      { id: "v-cola", name: "V Cola", nameAr: "في كولا", price: 40 },
      { id: "twist", name: "Twist", nameAr: "تويست", price: 40 },
      { id: "fury", name: "Fury", nameAr: "فيوري", price: 40 },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    nameAr: "الحلويات",
    icon: "",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&q=80",
    items: [
      { id: "cheesecake", name: "Cheesecake", nameAr: "شيز كيك", price: 65 },
      { id: "eclair-cake", name: "Eclair Cake", nameAr: "اكلير كيك", price: 50 },
      { id: "molten-cake", name: "Molten Cake", nameAr: "مولتن كيك", price: 75 },
      { id: "despacito", name: "Despacito", nameAr: "ديسباسيتو", price: 100 },
      { id: "vanroll", name: "Vanroll", nameAr: "فاترول", price: 75 },
      { id: "nutella-casserole", name: "Nutella Casserole", nameAr: "طاجن نوتيلا", price: 55 },
      { id: "om-ali", name: "Om Ali", nameAr: "ام علي", price: 55 },
      { id: "zashtota", name: "Zashtota", nameAr: "قشطوطة", price: 75 },
      { id: "mousse-cake", name: "Mousse Cake", nameAr: "موس كيك", price: 65 },
    ],
  },
  {
    id: "fried-chicken",
    name: "Fried Chicken",
    nameAr: "فرايد تشيكن",
    icon: "",
    image: "https://png.pngtree.com/background/20230613/original/pngtree-the-tyson-chicken-burger-with-lettuce-picture-image_3386442.jpg?w=400&q=80",
    items: [
      { id: "ranch-chicken", name: "Ranch", nameAr: "رانش", description: "Fried chicken piece, ranch sauce, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلي صوص رانش مايونيز - خس - طماطم - خيار", price: 100 },
      { id: "chicken-cheese-409", name: "Chicken Cheese 409", nameAr: "تشيكن تشيز 409", description: "Fried chicken, mozzarella sticks, mayo, lettuce, tomato, cucumber, cheese slice, cheese sauce", descriptionAr: "قطعة دجاج مقلي - اصابع موزاريلا مقلية - مايونيز - خس - طماطم - خيار - شريحة جبنه - صوص جبنه", price: 110 },
      { id: "classic-409", name: "Classic 409", nameAr: "كلاسيك 409", description: "Fried chicken, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج - مايونيز - خس - طماطم - خيار", price: 80 },
      { id: "chicken-mushroom", name: "Chicken Mushroom", nameAr: "تشيكن مشروم", description: "Fried chicken, mushroom, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلي مشروم مايونيز - خس - طماطم - خيار", price: 110 },
      { id: "roof-409-chicken", name: "Roof 409", nameAr: "روف 409", description: "Fried chicken, grilled burger patty, ranch sauce, smoked beef, mayo, texas sauce, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلي - و قطعة برجر مشوي - صوص رانش - بيف مدخن - مايونيز - صوص تكساس - خس - طماطم - خيار", price: 185 },
      { id: "super-crunchy", name: "Super Crunchy", nameAr: "سوبر كرانشي", description: "Fried chicken, 409 sauce, smoked turkey, lettuce, cucumber, tomato", descriptionAr: "قطعة دجاج - صوص 409 - رومي مدخن - خس - خيار - طماطم", price: 100 },
      { id: "mix-fried", name: "Mix Fried", nameAr: "ميكس فرايد", description: "Fried chicken, hot dog, BBQ sauce, cheese slice, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلي - هوت دوج - صوص باربكيو - شريحة جبن - مايونيز - خس - طماطم - خيار", price: 110 },
      { id: "bbq-409", name: "BBQ 409", nameAr: "باربكيو 409", description: "Fried chicken, BBQ sauce, smoked turkey, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلي - صوص باربكيو - تركي مدخن - مايونيز - خس - طماطم - خيار", price: 100 },
      { id: "bulldozer", name: "Bulldozer", nameAr: "بلدوزر", description: "Fried chicken, cheese, mozzarella sticks, mayo, lettuce, tomato, cucumber", descriptionAr: "قطعة دجاج مقلى - جبنه - اصابع موزاريلا - مايونيز - خس - طماطم - خيار", price: 105 },
      { id: "magico", name: "Magico", nameAr: "ماجيكو", description: "Fried chicken, cheese sauce, smoked turkey, jalapeno, cheese slice, lettuce, tomato, cucumber, mayo, mozzarella sticks", descriptionAr: "قطعة دجاج مقلي - صوص جبنة - تركي مدخن - فلفل هالبينو - شريحة جبنة - خس - طماطم - خيار - مايونيز - اصابع موتزريلا", price: 120 },
    ],
  },
  {
    id: "beef-burger",
    name: "Beef Burger",
    nameAr: "برجر لحمة",
    icon: "",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80",
    items: [
      { id: "mushroom-burger", name: "Mushroom Burger", nameAr: "مشروم برجر", description: "Grilled beef patty, mayo, lettuce, tomato, cucumber, mushroom sauce, mushroom, texas sauce", descriptionAr: "قطعة لحم مشوي - مايونيز - خس - طماطم - خيار - صوص مشروم - مشروم - صوص تكساس", price: 120 },
      { id: "fire-burger", name: "Fire Burger", nameAr: "فاير برجر", description: "Grilled beef, mayo, lettuce, tomato, cucumber, fire sauce, beef bacon, cheese sauce, jalapeno, texas sauce", descriptionAr: "قطعة لحم مشوي - مايونيز - خس - طماطم - خيار - صوص فاير حار - بيف بيكون - صوص جبنة - فلفل هالبينو - صوص تكساس", price: 125 },
      { id: "classic-409-burger", name: "Classic 409 Burger", nameAr: "كلاسيك 409", description: "Grilled beef, mayo, lettuce, tomato, cucumber, texas sauce", descriptionAr: "قطعة لحم مشوي - مايونيز - خس - طماطم - خيار - صوص تكساس", price: 105 },
      { id: "cheese-burger", name: "Cheese Burger", nameAr: "تشيز برجر", description: "Grilled beef, mozzarella sticks, mayo, lettuce, tomato, cucumber, cheese sauce, cheese slice, texas sauce", descriptionAr: "ق��عة لحم مشوي - اصابع موتزريلا - مايونيز - خس - طماطم - خيار - صوص جبنه - شريحة جبن - صوص تكساس", price: 135 },
      { id: "sniper-beef", name: "Sniper Beef", nameAr: "سنايبر برجر", description: "Grilled beef, texas sauce, lettuce, tomato, cucumber, mayo, beef bacon", descriptionAr: "قطعة لحم مشوي - صوص تكساس - خس - طماطم - خيار - مايونيز - بيف بيكون", price: 130 },
    ],
  },
  {
    id: "meals",
    name: "Meals",
    nameAr: "الوجبات",
    icon: "",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400&q=80",
    items: [
      { id: "broasted-2pcs", name: "Broasted 2 Pcs", nameAr: "بروست 2 قطعة", description: "2 chicken pieces, fries, ketchup sauce, bread", descriptionAr: "2 قطعة فراخ - بطاطس - صوص كاتشب - عيش", price:125 },
      { id: "broasted-3pcs", name: "Broasted 3 Pcs", nameAr: "بروست 3 قطعة", description: "3 chicken pieces, fries, coleslaw sauce, ketchup, bread", descriptionAr: "3 قطعة فراخ - بطاطس - صوص كول سلو - كاتشب - عيش", price: 160 },
      { id: "broasted-4pcs", name: "Broasted 4 Pcs", nameAr: "بروست 4 قطعة", description: "4 chicken pieces, fries, coleslaw sauce, ketchup, bread", descriptionAr: "4 قطعة فراخ - بطاطس - صوص كول سلو - كاتشب - عيش", price: 175 },
      { id: "broasted-8pcs", name: "Broasted 8 Pcs", nameAr: "بروست 8 قطعة", description: "8 chicken pieces, fries, sauce, coleslaw, ketchup, bread", descriptionAr: "8 قطعة فراخ - بطاطس - صوص - كول سلو - كاتشب - عيش", price: 340 },
      { id: "broasted-12pcs", name: "Broasted 12 Pcs", nameAr: "بروست 12 قطعة", description: "12 chicken pieces, fries, sauce, coleslaw, ketchup, bread", descriptionAr: "12 قطعة فراخ - بطاطس - صوص - كول سلو - كاتشب - عيش", price: 530 },
      { id: "strips-meal", name: "Strips Meal", nameAr: "وجبة استريبس", description: "4 strips pieces, fries, sauce, ketchup, bread", descriptionAr: "4 قطع استريبس - بطاطس - صوص - كاتشب - عيش", price: 150 },
    ],
  },
  {
    id: "kids-meals",
    name: "Kids Meals",
    nameAr: "وجبات كيدز",
    icon: "",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuD1t6klKBwzWvme-1vDAplYjv8-lY88Frcw&s",
    items: [
      { id: "kids-409", name: "Kids 409", nameAr: "كيدز 409", description: "2 strips pieces, juice, sauce, kids toy, bread", descriptionAr: "2 قطع استريبس - عصير - صوص - لعبة اطفال - عيش", price: 120 },
      { id: "kids-nuggets", name: "Kids Nuggets", nameAr: "ناجتس", description: "2 nuggets pieces, juice, sauce, kids toy, bread", descriptionAr: "2 قطع ناجتس - عصير - صوص - لعبة اطفال - عيش", price: 80 },
      { id: "mini-burger", name: "Mini Burger", nameAr: "ميني برجر", description: "1 burger piece, juice, cheese sauce, kids toy, mayo", descriptionAr: "1 قطعة برجر - عصير - صوص جبنة - لعبة اطفال - مايونيز", price: 65 },
      { id: "mini-chicken", name: "Mini Chicken", nameAr: "ميني شيكن", description: "1 chicken piece, juice, cheese sauce, kids toy, mayo", descriptionAr: "1 قطعة برجر - عصير - صوص جبنة - لعبة اطفال - مايونيز", price: 60 },
    ],
  },
  {
    id: "salad",
    name: "Salad",
    nameAr: "سلطة",
    icon: "",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80",
    items: [
      { id: "healthy-salad", name: "Healthy Salad", nameAr: "هيلثي", description: "Cucumber, tomato, lettuce, mushroom, white corn, black olives, olive oil", descriptionAr: "خيار - طماطم - خس - مشروم - وايتكورن - زيتون اسود - زيت زيتون", price: 65 },
      { id: "caesar-classic", name: "Caesar Classic", nameAr: "سيزر كلاسيك", description: "Lettuce, toast bread, caesar sauce, parmesan cheese", descriptionAr: "خس - عيش توست - صوص سيزر - بريميزاك تشيز", price: 65 },
      { id: "chicken-caesar", name: "Chicken Caesar", nameAr: "شيكن سيزر", description: "Lettuce, toast bread, caesar sauce, grilled chicken, parmesan cheese", descriptionAr: "خس - عيش توست - صوص سيزر - فراخ جريل - بريميزاك تشيز", price: 80 },
      { id: "chicken-bbq-salad", name: "Chicken BBQ Salad", nameAr: "شيكن باربيكيو", description: "Lettuce, toast bread, caesar sauce, chicken, parmesan cheese", descriptionAr: "خس - عيش توست - صوص سيزر - فراخ - بريميزاك تشيز", price: 80 },
      { id: "greek-salad", name: "Greek Salad", nameAr: "جريك", description: "Lettuce, cucumber, black olives, colored peppers, feta cheese", descriptionAr: "خس - خيار - زيتون اسود - فلفل الوان - فيتا تشيز", price: 70 },
    ],
  },
  {
    id: "sweet-pie",
    name: "Sweet Pie",
    nameAr: "فطير حلو",
    icon: "",
    image: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=400&q=80",
    items: [
      { id: "bougasa-pie", name: "Bougasa Pie", nameAr: "فطير بوغاسة", description: "Powdered sugar, milk", descriptionAr: "سكر بودر - لبن", price: 80 },
      { id: "nut-custard-pie", name: "Nut Custard Pie", nameAr: "فطير كاستر مكسرات", description: "Custard, nuts, milk", descriptionAr: "كاستر - مكسرات - لبن", price: 90 },
      { id: "banana-nutella-pie", name: "Banana Nutella Pie", nameAr: "فطير نوتيلا موز", description: "Nutella, banana, milk", descriptionAr: "نوتيلا - موز - لبن", price: 140 },
      { id: "lotus-custard-pie", name: "Lotus Custard Pie", nameAr: "فطير لوتس مكسرات", description: "Lotus, nuts, milk", descriptionAr: "لوتس - مكسرات - لبن", price: 150 },
    ],
  },
  {
    id: "grilled-sandwich",
    name: "Grilled Sandwich",
    nameAr: "سندويتش مشاوي",
    icon: "",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&q=80",
    items: [
      { id: "kofta-sandwich", name: "Kofta Sandwich", nameAr: "سندويتش كفتة", price: 70 },
      { id: "shish-sandwich", name: "Shish Sandwich", nameAr: "سندويتش شيش", price: 70 },
      { id: "hawawshi-sandwich", name: "Hawawshi Sandwich", nameAr: "سندويتش حواوشي", price: 80 },
    ],
  },
  {
    id: "pizza",
    name: "Pizza",
    nameAr: "بيتزا",
    icon: "",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
    items: [
  { id: "chicken-pizza", name: "Chicken", nameAr: "فراخ", price: 135 },
  { id: "mix-chicken-pizza", name: "Mix Chicken", nameAr: "ميكس فراخ", price: 155 },
  { id: "meat-pizza", name: "Meat", nameAr: "لحمة", price: 135 },
  { id: "meat-mix-pizza", name: "Meat Mix", nameAr: "ميكس لحوم", price: 155 },
  { id: "margarita-pizza", name: "Margarita", nameAr: "مارجريتا", price: 105 },
  { id: "mix-cheese-pizza", name: "Mix Cheese", nameAr: "ميكس جبن", price: 105 },
  { id: "susis-pizza", name: "Susis", nameAr: "سوسيس", price: 125 },
  { id: "vegetable-pizza", name: "Vegetable", nameAr: "خضار", price: 105 },
  { id: "sea-food-pizza", name: "Sea Food", nameAr: "تونة", price: 135 },
  { id: "mushrooms-pizza", name: "Mushrooms", nameAr: "مشروم", price: 115 },
  { id: "crunchy-pizza", name: "Crunchy", nameAr: "كرانشي", price: 150 },
  { id: "roof-409-pizza", name: "Roof 409", nameAr: "روف 409", price: 170 },
  { id: "sausage-pizza", name: "Sausage", nameAr: "سجق", price: 125 },
  { id: "pastrami-pizza", name: "Pastrami", nameAr: "بسطرمه", price: 135 },
  { id: "chicken-cheddar-pizza", name: "Chicken Cheddar", nameAr: "شيكن شيدر", price: 150 },
  { id: "salami-pizza", name: "Salami", nameAr: "سلامي", price: 145 },
  { id: "mix-smoked-turkey-pizza", name: "Mix Smoked Turkey", nameAr: "تركي مدخن", price: 160 },
  { id: "chicken-bbq-pizza", name: "Chicken BBQ", nameAr: "شيكن باربيكيو", price: 150 },
  { id: "chicken-ranch-pizza", name: "Chicken Ranch", nameAr: "شيكن رانش", price: 150 },
],
  },
  {
    id: "oriental-pizza",
    name: "Oriental Pizza",
    nameAr: "بيتزا شرقي",
    icon: "",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
    items: [
  { id: "oriental-chicken", name: "Chicken", nameAr: "فراخ", price: 145 },
  { id: "oriental-chicken-mix", name: "Chicken Mix", nameAr: "ميكس فراخ", price: 165 },
  { id: "oriental-meat", name: "Meat", nameAr: "لحمة", price: 145 },
  { id: "oriental-meat-mix", name: "Meat Mix", nameAr: "ميكس لحوم", price: 165 },
  { id: "oriental-pastrami", name: "Pastrami", nameAr: "بسطرمة", price: 160 },
  { id: "oriental-sausage", name: "Sausage", nameAr: "سجق", price: 140 },
  { id: "oriental-susis", name: "Susis", nameAr: "سوسيس", price: 130 },
  { id: "oriental-roof-409", name: "Roof 409", nameAr: "روف 409", price: 180 },
  { id: "oriental-extra-meat", name: "Extra Meat", nameAr: "اكسترا لحوم", price: 200 },
  { id: "oriental-sausage-pastrami", name: "Mix", nameAr: "سجق بسطرمة كيري", price: 200 },
  { id: "oriental-cheese-mix", name: "Cheese Mix", nameAr: "ميكس جبن", price: 135 },
],
  },
  {
    id: "wrap",
    name: "Wrap",
    nameAr: "تشيكن راب",
    icon: "",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&q=80",
    items: [
      { id: "smoke-wrap", name: "Smoke Wrap", nameAr: "سموك راب", description: "Crispy chicken, lettuce, cucumber, tomato, smoked beef, cheese slice", descriptionAr: "فراخ كريسبي - خس - خيار - طماطم - بيف مدخن - شريحه جبنه", price: 115 },
      { id: "wrap-fries", name: "Wrap Fries", nameAr: "بطاطس راب", description: "Fries, mayo, lettuce, cucumber, tomato", descriptionAr: "بطاطس - مايونيز - خس - خيار - طماطم", price: 80 },
      { id: "chicken-wrap", name: "Chicken Wrap", nameAr: "تشيكن راب", description: "Crispy chicken, mayo, lettuce, cucumber", descriptionAr: "فراخ كريسبي - مايونيز - خس - خيار", price: 100 },
      { id: "supreme-wrap", name: "Supreme Wrap", nameAr: "سوبريم راب", description: "Crispy chicken, lettuce, cucumber, mayo, turkey, tomato", descriptionAr: "فراخ كريسبي - خس - خيار - مايونيز - تركي - طماطم", price: 120 },
      { id: "shawarma-wrap", name: "Shawarma Wrap", nameAr: "شاورما راب", description: "Shawarma, lettuce, cucumber, mayo, turkey, tomato, texas sauce", descriptionAr: "شاورما - خس - خيار - مايونيز - تركي - طماطم - تكساس", price: 110 },
    ],
  },
  {
    id: "crepe",
    name: "Crepe",
    nameAr: "كريب",
    icon: "",
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400&q=80",
    items: [
  { id: "shawarma-crepe", name: "Shawarma Crepe", nameAr: "كريب شاورما", price: 105 },
  { id: "strips-crepe", name: "Strips Crepe", nameAr: "كريب استربس", price: 105 },
  { id: "sausage-crepe", name: "Sausage Crepe", nameAr: "كريب سوسيس", price: 95 },
  { id: "potato-crepe", name: "Potato Crepe", nameAr: "كريب بطاطس", price: 85 },
  { id: "mix-cheese-crepe", name: "Mix Cheese Crepe", nameAr: "كريب ميكس جبن", price: 100 },
  { id: "meat-mix-crepe", name: "Meat Mix Crepe", nameAr: "كريب ميكس لحوم", price: 120 },
  { id: "mix-chicken-crepe", name: "Mix Chicken Crepe", nameAr: "كريب ميكس فراخ", price: 120 },
  { id: "mushroom-crepe", name: "Mushroom Crepe", nameAr: "كريب مشروم", price: 100 },
  { id: "susis-crepe", name: "Susis Crepe", nameAr: "كريب سوسيس", price: 95 },
  { id: "cordon-bleu-crepe", name: "Cordon Bleu Crepe", nameAr: "كريب كوردون بلو", price: 115 },
  ],
  },
  {
    id: "pasta",
    name: "Pasta & Risotto",
    nameAr: "باستا وريزو",
    icon: "",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80",
    items: [
      { id: "sausage-pasta", name: "Sausage Pasta", nameAr: "باستا سجق", description: "Penne pasta, cream sauce, sausage", descriptionAr: "مكرونة بنا - صوص كريمة - سجق", price: 100 },
      { id: "pastrami-pasta", name: "Pastrami Pasta", nameAr: "باستا بسطرمة", description: "Penne pasta, cream sauce, pastrami", descriptionAr: "مكرونة بنا - صوص كريمة - بسطرمة", price: 125 },
      { id: "bachamel-pasta", name: "Bachamel Pasta", nameAr: "باستا بشاميل", description: "Penne pasta, cream sauce, meat", descriptionAr: "مكرونة بنا - صوص كريمة - لحمة", price: 110 },
      { id: "shrimp-pasta", name: "Shrimp Pasta", nameAr: "باستا شرمب", description: "Penne pasta, cream sauce, shrimp, colored peppers", descriptionAr: "مكرونة بنا - صوص كريمة - جمبري - فلفل الوان", price: 210 },
      { id: "fried-chicken-pasta", name: "Fried Chicken Pasta", nameAr: "باستا فرايد تشيكن", description: "Penne pasta, crispy chicken pieces, cream sauce", descriptionAr: "مكرونة بنا - قطع فراخ كرسبي - صوص كريمة", price: 110 },
      { id: "negresco", name: "Negresco", nameAr: "نجرسكو", price: 110 },
      { id: "red-sauce-pasta", name: "Red Sauce Pasta", nameAr: "مكرونة ريد صوص 409", description: "Penne pasta, red sauce", descriptionAr: "مكرونة بنا - ريد صوص", price: 60 },
      { id: "white-sauce-pasta", name: "White Sauce Pasta", nameAr: "مكرونة وايت صوص", description: "Penne pasta, white sauce", descriptionAr: "مكرونة بنا - وايت صوص", price: 75 },
      { id: "bolognese-pasta", name: "Bolognese Pasta", nameAr: "مكرونة بلونيز", description: "Penne pasta, red sauce, meat, peppers", descriptionAr: "مكرونة بنا - ريد صوص - لحمة - فلفل", price: 100 },
      { id: "alfredo-pasta", name: "Alfredo Pasta", nameAr: "مكرونة الفريدو", description: "Penne pasta, cream sauce, chicken, mushroom", descriptionAr: "مكرونة بنا - صوص كريمة - فراخ - مشروم", price: 120 },
      { id: "rizzo-tiger", name: "Rizzo Tiger", nameAr: "ريزو تايجر", description: "Basmati rice, crispy chicken", descriptionAr: "ارز بسمتي - فراخ كريسبي", price: 100 },
      { id: "rizzo-plain", name: "Rizzo Plain", nameAr: "ريزو", description: "Basmati rice", descriptionAr: "ارز بسمتي", price: 60 },
    ],
  },
  {
    id: "extras",
    name: "Extras",
    nameAr: "اضافات",
    icon: "",
    image: "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=400&q=80",
    items: [
      { id: "vegetable-salad", name: "Vegetable Salad", nameAr: "سلطة خضار", price: 20 },
      { id: "sumac-salad", name: "Sumac Salad", nameAr: "سلطة سماق", price: 25 },
      { id: "tahini", name: "Tahini", nameAr: "طحينة", price: 20 },
      { id: "extra-cheese", name: "Extra Cheese", nameAr: "اكسترا جبن", price: 20 },
      { id: "potatos", name: "Potatos", nameAr: "بطاطس", price: 35 },
      { id: "fries-cheese-bacon", name: "Fries Cheese Bacon", nameAr: "فرايز تشيز بيكون", price: 80 },
      { id: "coleslaw", name: "Coleslaw", nameAr: "كول سلو", price: 20 },
      { id: "cheese-sauce", name: "Cheese Sauce", nameAr: "صوص جبن", price: 20 },
      { id: "fire-sauce", name: "Fire Sauce", nameAr: "صوص فاير", price: 20 },
      { id: "ranch-sauce", name: "Ranch Sauce", nameAr: "صوص رانش", price: 20 },
      { id: "bbq-sauce", name: "BBQ Sauce", nameAr: "صوص باربيكيو", price: 20 },
      { id: "bread", name: "Bread", nameAr: "عيش", price: 5 },
      { id: "kiri", name: "Kiri", nameAr: "كيري", price: 25 },
    ],
    
  },
];

